#! /usr/bin/env bash

echo "AUTOGRADER SCRIPT"

# Always pull the src from github.
git clone --depth=1 --branch=master https://github.com/saasbook/gradescope-ci-autograder
# cp -r gradescope-ci-autograder/src/script/* script/

gradescope-ci-autograder/src/script/pre-install.sh

# mkdir -p src/results/

echo "System Ruby"
ruby -v
echo "/bin/bash -l -c version of ruby:"
/bin/bash -l -c "ruby -v"

/bin/bash -l -c "ruby gradescope-ci-autograder/src/script/autograder.rb $PWD/submission/ $PWD/results/results.json"
# cp src/results/results.json results/

# rm -rf gradescope-ci-autograder/
